"""Cross-language fixture parity: Python SDK must recompute spec/fixtures fingerprints.

This file is the Python side of the cross-SDK parity contract. Prompt C (sanna-ts)
adds the TS mirror. Together they prove the two SDKs agree on fingerprint computation.
"""
import json
from pathlib import Path

import pytest


def _load_fixture(name: str) -> dict:
    path = Path("spec/fixtures/receipts") / name
    if not path.exists():
        pytest.skip(f"Fixture not found: {path}")
    return json.loads(path.read_text())


def test_full_featured_cv10_fingerprint_parity():
    """Python verifier recomputes full-featured.json (cv=10) fingerprint byte-equal."""
    from sanna.verify import verify_receipt, load_schema, _verify_fingerprint_v013

    fixture = _load_fixture("full-featured.json")
    assert fixture.get("checks_version") == "10", "Fixture must be cv=10 (post-Prompt-A)"
    assert fixture.get("agent_identity"), "Fixture must have agent_identity"

    matches, computed_short, expected_short = _verify_fingerprint_v013(fixture)
    assert matches, (
        f"Fingerprint mismatch: computed={computed_short!r} expected={expected_short!r}"
    )

    expected_full = fixture.get("full_fingerprint", "")
    if expected_full:
        from sanna.hashing import hash_text
        from sanna.verify import _verify_fingerprint_v013
        matches2, short2, _ = _verify_fingerprint_v013(fixture)
        assert matches2

    result = verify_receipt(fixture, load_schema())
    assert result.valid, result.errors


def test_pass_single_check_cv10_fingerprint_parity():
    """Python verifier recomputes pass-single-check.json (cv=10) fingerprint byte-equal."""
    from sanna.verify import verify_receipt, load_schema, _verify_fingerprint_v013

    fixture = _load_fixture("pass-single-check.json")
    assert fixture.get("checks_version") == "10", "Fixture must be cv=10 (post-Prompt-A)"

    matches, computed_short, expected_short = _verify_fingerprint_v013(fixture)
    assert matches, (
        f"Fingerprint mismatch: computed={computed_short!r} expected={expected_short!r}"
    )

    result = verify_receipt(fixture, load_schema())
    assert result.valid, result.errors


def test_constitution_signable_byte_parity_san_490():
    """SAN-490: Python's constitution_to_signable_dict bytes match the cross-SDK
    byte-equal contract for all 5 vectors.

    Forward-protecting canary: catches any future Python SDK refactor that
    changes canonicalization. The fixture was generated by Python's reference
    implementation in sanna-protocol PR #35 (merged at 3aea629), so by
    construction Python's output matches today; this test makes that match
    enforced rather than assumed.
    """
    import hashlib
    import json
    from pathlib import Path

    from sanna.constitution import parse_constitution, constitution_to_signable_dict
    from sanna.hashing import canonical_json_bytes

    vectors_path = Path("spec/fixtures/constitution-signable-vectors.json")
    if not vectors_path.exists():
        pytest.skip(f"Vectors file not found: {vectors_path}")

    vectors_doc = json.loads(vectors_path.read_text())

    required_ids = {
        "must_escalate_target_no_optionals",
        "must_escalate_target_url_only",
        "must_escalate_target_handler_only",
        "must_escalate_target_null",
        "must_escalate_target_all_fields",
    }
    seen_ids = set()

    for v in vectors_doc["vectors"]:
        vid = v["id"]
        seen_ids.add(vid)

        const = parse_constitution(v["input_constitution"])
        signable = constitution_to_signable_dict(const, signing_version=1)
        canonical_bytes = canonical_json_bytes(signable)
        canonical_str = canonical_bytes.decode("utf-8")

        assert canonical_str == v["expected_signable_canonical_json"], (
            f"Vector {vid!r}: canonical signable bytes diverge from fixture"
        )

        actual_sha256 = hashlib.sha256(canonical_bytes).hexdigest()
        assert actual_sha256 == v["expected_signable_sha256"], (
            f"Vector {vid!r}: SHA-256 diverges"
        )

    missing = required_ids - seen_ids
    assert not missing, f"Vectors fixture missing required ids: {missing}"


def test_constitution_signable_byte_parity_v2_san_492():
    """SAN-492: Python's v2 canonical bytes match the cross-SDK byte-equal contract for all 20 vectors.

    The reference is spec/fixtures/constitution-signable-vectors-v2.json (generated by
    sanna-protocol's tools/generate_signable_vectors_v2.py, which IS the v2 reference
    implementation). Python's _constitution_to_signable_dict_v2 must produce
    byte-identical output for the same input.
    """
    import hashlib
    import json
    from pathlib import Path

    from sanna.constitution import parse_constitution, constitution_to_signable_dict
    from sanna.hashing import canonical_json_bytes

    vectors_path = Path("spec/fixtures/constitution-signable-vectors-v2.json")
    if not vectors_path.exists():
        pytest.skip(f"v2 vectors file not found: {vectors_path}")

    vectors_doc = json.loads(vectors_path.read_text())
    assert vectors_doc["signing_version"] == 2

    seen_ids = set()
    for v in vectors_doc["vectors"]:
        vid = v["id"]
        seen_ids.add(vid)

        const = parse_constitution(v["input_constitution"])
        signable = constitution_to_signable_dict(const, signing_version=2)
        canonical_bytes = canonical_json_bytes(signable)
        canonical_str = canonical_bytes.decode("utf-8")

        assert canonical_str == v["expected_signable_canonical_json"], (
            f"Vector {vid!r}: canonical signable bytes diverge from fixture"
        )

        actual_sha256 = hashlib.sha256(canonical_bytes).hexdigest()
        assert actual_sha256 == v["expected_signable_sha256"], (
            f"Vector {vid!r}: SHA-256 diverges"
        )

    assert len(seen_ids) == 20, f"Expected 20 vectors, got {len(seen_ids)}"


def test_constitution_v1_verification_preserved_san_492():
    """SAN-492: v1-signed test fixtures continue to verify under v1 dispatch.

    Backwards-compat canary: the v1 path must remain frozen-per-SDK so all
    currently-signed customer constitutions verify unchanged.
    """
    from pathlib import Path
    from sanna.constitution import load_constitution
    from sanna.crypto import verify_constitution_full

    yaml_path = Path("spec/fixtures/constitutions/minimal.yaml")
    if not yaml_path.exists():
        pytest.skip(f"v1 fixture not found: {yaml_path}")

    pub_path = Path("spec/fixtures/keypairs/test-author.pub")
    if not pub_path.exists():
        pytest.skip(f"public key not found: {pub_path}")

    const = load_constitution(yaml_path)
    assert const.provenance.signature.scheme == "constitution_sig_v1"
    assert verify_constitution_full(const, pub_path), (
        "v1 fixture must verify under v1 dispatch -- backwards-compat broken"
    )
