"""Property-based tests for Sanna crypto primitives (SAN-293).

Complements fixture-based coverage in tests/test_crypto_integrity.py
and tests/test_fingerprint_edge_cases.py with Hypothesis-generated
random-input invariant assertions.

Ten property categories, each in its own test class:

1.  TestCanonicalJsonDeterminism: canonical_json_bytes invariant
    under dict key reordering
2.  TestNfcScope: hash_text invariant under NFC<->NFD; hash_obj
    byte-different across NFC<->NFD (ADR-004 normative)
3.  TestFingerprintStability:
    3a. _verify_fingerprint_v013 deterministic on repeat calls
    3b. computed fingerprint stable across canonical-JSON round-trip
4.  TestEmptyContainerHandling: [] vs null produces distinct hashes
    for parent_receipts; non-empty string vs null for workflow_id
5.  TestFloatHandling:
    5a. integer-valued floats coerce to int (positive)
    5b. non-integer floats raise (negative)
6.  TestSpecialFloatRejection:
    6a. NaN raises
    6b. +Infinity raises
    6c. -Infinity raises
7.  TestSignatureRoundTrip: sign_bytes + verify_signature on
    arbitrary bytes; tampered-byte AND tampered-signature both fail.
    Receipt-level signing is covered by fixture tests in
    test_crypto_integrity.py and is intentionally not duplicated here.
8.  TestFieldCountDispatch: cv-aware dispatch produces 12/14/14/16/20/21
    field fingerprint for cv=5/6/7/8/9/10 respectively (externally
    observed via differential receipts; see test docstring for
    methodology)
9.  TestRedactionMarkerShape: redaction marker
    {__redacted__: True, original_hash: <sha256-hex>} byte-stable
    across input string variations (Spec section 2.11.1)
10. TestFingerprintCrossSiteParity: receipts generated by
    generate_receipt() pass verify_fingerprint() (emission/
    verification parity; fallback from direct identity check since
    there is no single centralized compute_fingerprint callable)

CI runs default 100 examples per test. Override via
SANNA_HYPOTHESIS_MAX_EXAMPLES env var for nightly extended runs.
"""

import base64
import hashlib
import json
import os
import unicodedata

import pytest
from hypothesis import HealthCheck, example, given, settings, strategies as st, assume

_MAX_EXAMPLES = int(os.environ.get("SANNA_HYPOTHESIS_MAX_EXAMPLES", "100"))
settings.register_profile(
    "sanna_default",
    max_examples=_MAX_EXAMPLES,
    deadline=None,  # crypto ops can be slow on individual examples
    suppress_health_check=[
        HealthCheck.too_slow,
        HealthCheck.filter_too_much,  # NFC test uses assume(); dispatch tests too
    ],
)
settings.load_profile("sanna_default")

from sanna.hashing import (
    EMPTY_HASH,
    canonical_json_bytes,
    hash_obj,
    hash_text,
    sha256_hex,
)
from sanna.crypto import sign_bytes, verify_signature
from sanna.redaction import _make_redaction_marker
from sanna.verify import _verify_fingerprint_v013


# ---------------------------------------------------------------------------
# Shared strategies
# ---------------------------------------------------------------------------

# Filter out lone surrogates (Unicode category Cs); they are not valid in
# JSON, so canonical_json_bytes raises on them. They are out of scope for
# the canonicalization invariants we are testing.
json_safe_text = st.text(
    alphabet=st.characters(blacklist_categories=("Cs",)),
    max_size=200,
)

_json_primitives = st.one_of(
    st.none(),
    st.booleans(),
    st.integers(min_value=-(2**53) + 1, max_value=(2**53) - 1),
    json_safe_text,
)


def json_values():
    """Recursive JSON-compatible structures, depth <= 4."""
    return st.recursive(
        _json_primitives,
        lambda children: st.one_of(
            st.lists(children, max_size=8),
            st.dictionaries(
                st.text(
                    min_size=1,
                    max_size=20,
                    alphabet=st.characters(blacklist_categories=("Cs",)),
                ),
                children,
                max_size=8,
            ),
        ),
        max_leaves=20,
    )


# Minimal receipt dict for cv=6 (14-field formula).
# Pipe is banned from correlation_id per FIX-33.
# receipt_fingerprint and full_fingerprint are left empty because
# _verify_fingerprint_v013 computes and returns its own value independently
# of the stored receipt_fingerprint field.
_cv6_receipt_strategy = st.fixed_dictionaries({
    "correlation_id": st.text(
        alphabet=st.characters(
            blacklist_categories=("Cs",),
            blacklist_characters=("|",),
        ),
        max_size=50,
    ),
    "context_hash": st.just(EMPTY_HASH),
    "output_hash": st.just(EMPTY_HASH),
    "checks_version": st.just("6"),
    "checks": st.just([]),
    "parent_receipts": st.one_of(
        st.none(),
        st.lists(
            st.text(
                max_size=20,
                alphabet=st.characters(blacklist_categories=("Cs",)),
            ),
            max_size=3,
        ),
    ),
    "workflow_id": st.one_of(
        st.none(),
        st.text(
            max_size=30,
            alphabet=st.characters(blacklist_categories=("Cs",)),
        ),
    ),
    "receipt_fingerprint": st.just(""),
    "full_fingerprint": st.just(""),
})


def _make_base_receipt(cv: str) -> dict:
    """Build a minimal valid receipt dict for _verify_fingerprint_v013 at given cv."""
    base: dict = {
        "correlation_id": "test-pbt-corr",
        "context_hash": EMPTY_HASH,
        "output_hash": EMPTY_HASH,
        "checks_version": cv,
        "checks": [],
        "receipt_fingerprint": "",
        "full_fingerprint": "",
    }
    cv_int = int(cv)
    if cv_int >= 6:
        base["parent_receipts"] = None
        base["workflow_id"] = None
    if cv_int >= 8:
        base["enforcement_surface"] = "middleware"
        base["invariants_scope"] = "full"
    if cv_int >= 9:
        base["tool_name"] = "sanna"
    if cv_int >= 10:
        base["agent_identity"] = {"agent_session_id": "sn_ag_pbt_base"}
    return base


# ---- 1. Canonical JSON determinism ----

class TestCanonicalJsonDeterminism:
    """canonical_json_bytes is invariant under semantically-equivalent
    reordering of dict keys at any nesting level.

    Spec Section 3: Canonical JSON requires sort_keys=True at all depths.
    """

    @given(json_values())
    def test_dict_reordering_invariant(self, obj):
        """Reversed-key clone must produce byte-identical canonical JSON."""
        from copy import deepcopy

        def reverse_keys(o):
            if isinstance(o, dict):
                return {k: reverse_keys(v) for k, v in reversed(list(o.items()))}
            if isinstance(o, list):
                return [reverse_keys(e) for e in o]
            return o

        shuffled = reverse_keys(deepcopy(obj))
        assert canonical_json_bytes(obj) == canonical_json_bytes(shuffled), (
            "canonical_json_bytes must be invariant under dict key reordering "
            "at any nesting level"
        )


# ---- 2. NFC scope (ADR-004) ----

class TestNfcScope:
    """hash_text normalizes its input to NFC at the boundary, so NFC and
    NFD inputs hash identically. hash_obj does NOT normalize string values
    inside objects, so {k: NFC} and {k: NFD} differ in canonical JSON
    bytes and therefore in hash output.

    ADR-004: NFC Normalization Scope in Canonical JSON.
    See also tests/test_nfc_scope.py for fixture-based coverage.
    """

    @given(json_safe_text)
    def test_hash_text_nfc_invariant(self, s):
        """hash_text produces the same digest for NFC and NFD equivalents."""
        nfc = unicodedata.normalize("NFC", s)
        nfd = unicodedata.normalize("NFD", s)
        assert hash_text(nfc) == hash_text(nfd), (
            "hash_text must NFC-normalize at the boundary (ADR-004)"
        )

    # Known NFC/NFD-distinct example: e + combining acute accent -> e-acute.
    # The @example ensures the assertion executes at least once even if
    # Hypothesis does not happen to generate a combining character.
    @example("\xe9")
    @given(json_safe_text)
    def test_hash_obj_does_not_normalize_inside(self, s):
        """hash_obj must NOT NFC-normalize string values inside objects.

        ADR-004: NFC normalization is a hash_text boundary concern. Inside
        canonical_json_bytes, strings are preserved verbatim so that NFC
        and NFD representations remain distinguishable.
        """
        nfc = unicodedata.normalize("NFC", s)
        nfd = unicodedata.normalize("NFD", s)
        assume(nfc != nfd)
        assert hash_obj({"k": nfc}) != hash_obj({"k": nfd}), (
            "hash_obj must NOT NFC-normalize string values inside objects (ADR-004)"
        )


# ---- 3. Fingerprint stability ----

class TestFingerprintStability:
    """_verify_fingerprint_v013 produces the same computed fingerprint for
    the same input on repeated calls (3a) AND for inputs that survive
    a canonical-JSON round-trip unchanged (3b).

    3b catches subtle canonicalization bugs where parsing the canonical
    form back to a dict and re-computing changes the output. Note: there
    is no single centralized compute_fingerprint callable in the Python
    SDK; _verify_fingerprint_v013 is the authoritative re-computation
    path used by the offline verifier (see Property 10 for cross-site
    parity between emission and verification).
    """

    @given(_cv6_receipt_strategy)
    def test_deterministic_repeat(self, receipt):
        """Computed fingerprint is identical across two calls with the same dict."""
        _, fp1, _ = _verify_fingerprint_v013(receipt)
        _, fp2, _ = _verify_fingerprint_v013(receipt)
        assert fp1 == fp2, (
            "_verify_fingerprint_v013 must be deterministic on repeat calls"
        )

    @given(_cv6_receipt_strategy)
    def test_canonical_json_round_trip_stable(self, receipt):
        """Computed fingerprint is identical after canonical-JSON round-trip.

        The fingerprint formula hashes string fields (correlation_id, etc.)
        via hash_text and object/list fields via hash_obj. Both are pure
        functions of their inputs. A JSON round-trip preserves Python None
        (via JSON null) and string values, so the fingerprint must be stable.
        """
        round_tripped = json.loads(canonical_json_bytes(receipt).decode("utf-8"))
        _, fp_orig, _ = _verify_fingerprint_v013(receipt)
        _, fp_rt, _ = _verify_fingerprint_v013(round_tripped)
        assert fp_orig == fp_rt, (
            "computed fingerprint must be stable across canonical-JSON round-trip"
        )


# ---- 4. Empty container handling ----

class TestEmptyContainerHandling:
    """[] (empty array) and null (absent) MUST produce distinct computed
    fingerprints for container fields included in the formula.

    parent_receipts at cv>=6: None -> EMPTY_HASH, [] -> hash_obj([]).
    workflow_id at cv>=6: None -> EMPTY_HASH, non-empty str -> hash_text(str).
    These distinctions carry semantic meaning in the protocol.

    Note: hash_text("") == EMPTY_HASH (canonicalize_text("") returns ""
    and SHA-256 of b"" is the same sentinel). The empty-string/null
    distinction for workflow_id is therefore a code-path distinction
    only. This test uses a non-empty workflow_id to assert a meaningful
    hash difference.
    """

    def test_parent_receipts_empty_vs_null(self):
        """parent_receipts=[] and parent_receipts=None produce different fingerprints."""
        r_null = _make_base_receipt("6")
        r_null["parent_receipts"] = None

        r_empty = _make_base_receipt("6")
        r_empty["parent_receipts"] = []

        _, fp_null, _ = _verify_fingerprint_v013(r_null)
        _, fp_empty, _ = _verify_fingerprint_v013(r_empty)
        assert fp_null != fp_empty, (
            "parent_receipts=None and parent_receipts=[] must produce "
            "distinct fingerprints"
        )

    def test_workflow_id_non_empty_vs_null(self):
        """workflow_id='wf-001' and workflow_id=None produce different fingerprints.

        None -> EMPTY_HASH; 'wf-001' -> hash_text('wf-001') which is a
        different digest. The non-empty case is the semantically meaningful
        distinction in the protocol.
        """
        r_null = _make_base_receipt("6")
        r_null["workflow_id"] = None

        r_set = _make_base_receipt("6")
        r_set["workflow_id"] = "wf-001"

        _, fp_null, _ = _verify_fingerprint_v013(r_null)
        _, fp_set, _ = _verify_fingerprint_v013(r_set)
        assert fp_null != fp_set, (
            "workflow_id=None and workflow_id='wf-001' must produce "
            "distinct fingerprints"
        )

    def test_agent_identity_present_vs_absent_gates_cv10(self):
        """At cv=10, agent_identity absence causes the verifier to return empty.

        Spec section 2.19: agent_identity is required at cv=10. The verifier
        enforces this by returning (False, '', '') when agent_identity is
        absent or falsy. A valid cv=10 receipt with agent_identity produces
        a non-empty computed fingerprint.
        """
        r_with = _make_base_receipt("10")

        r_without = dict(r_with)
        del r_without["agent_identity"]

        _, fp_with, _ = _verify_fingerprint_v013(r_with)
        ok_without, fp_without, _ = _verify_fingerprint_v013(r_without)

        assert fp_with != "", (
            "cv=10 receipt with agent_identity should produce a non-empty fingerprint"
        )
        assert fp_without == "", (
            "cv=10 receipt missing agent_identity should return empty computed "
            "fingerprint per spec section 2.19 verifier enforcement"
        )


# ---- 5. Float handling ----

class TestFloatHandling:
    """Per spec Section 3: integer-valued floats (1.0) coerce to int (1)
    before canonicalization; non-integer floats (1.5) are rejected.
    """

    @given(st.integers(min_value=-(2**53) + 1, max_value=(2**53) - 1))
    def test_integer_valued_float_coerces_to_int(self, n):
        """float(n) and n must produce byte-identical canonical JSON."""
        assert canonical_json_bytes(float(n)) == canonical_json_bytes(n), (
            "integer-valued floats must coerce to int before canonicalization"
        )

    @given(
        st.floats(min_value=-1e6, max_value=1e6, allow_nan=False, allow_infinity=False)
    )
    def test_non_integer_float_rejected(self, f):
        """Non-integer floats must raise ValueError from canonical_json_bytes."""
        assume(f != int(f))
        with pytest.raises(ValueError, match="Non-integer float"):
            canonical_json_bytes(f)


# ---- 6. Special float rejection ----

class TestSpecialFloatRejection:
    """NaN, +Infinity, -Infinity MUST be rejected at canonicalization
    per spec Section 3. JSON does not support non-finite floats.
    """

    def test_nan_rejected(self):
        """canonical_json_bytes raises TypeError on NaN."""
        with pytest.raises(TypeError, match="Non-finite float"):
            canonical_json_bytes(float("nan"))

    def test_positive_infinity_rejected(self):
        """canonical_json_bytes raises TypeError on positive Infinity."""
        with pytest.raises(TypeError, match="Non-finite float"):
            canonical_json_bytes(float("inf"))

    def test_negative_infinity_rejected(self):
        """canonical_json_bytes raises TypeError on negative Infinity."""
        with pytest.raises(TypeError, match="Non-finite float"):
            canonical_json_bytes(float("-inf"))


# ---- 7. Signature round-trip ----

class TestSignatureRoundTrip:
    """sign_bytes + verify_signature round-trip on arbitrary bytes.
    Tampered message AND tampered signature both fail verification.

    Keypair is generated once per test class (scope='class') so that the
    example budget is spent on signing variation, not key generation.

    NOTE: receipt-level signing (sign_receipt / verify_receipt_signature)
    is covered by fixture tests in test_crypto_integrity.py and is
    intentionally not duplicated here. PBT here targets the primitive.
    """

    @pytest.fixture(scope="class")
    def keypair(self):
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
        private_key = Ed25519PrivateKey.generate()
        public_key = private_key.public_key()
        return private_key, public_key

    @given(st.binary(min_size=1, max_size=10_000))
    def test_sign_verify_round_trip(self, keypair, msg):
        """Signing then verifying any byte sequence returns True."""
        private_key, public_key = keypair
        sig_b64 = sign_bytes(msg, private_key)
        assert verify_signature(msg, sig_b64, public_key) is True, (
            "verify_signature must return True for a freshly signed message"
        )

    @given(msg=st.binary(min_size=1, max_size=10_000), data=st.data())
    def test_tampered_message_fails(self, keypair, msg, data):
        """Flipping one bit in the plaintext must fail verification."""
        private_key, public_key = keypair
        sig_b64 = sign_bytes(msg, private_key)
        byte_idx = data.draw(st.integers(min_value=0, max_value=len(msg) - 1))
        bit_idx = data.draw(st.integers(min_value=0, max_value=7))
        tampered = bytearray(msg)
        tampered[byte_idx] ^= (1 << bit_idx)
        assert verify_signature(bytes(tampered), sig_b64, public_key) is False, (
            "verify_signature must reject a tampered message"
        )

    @given(msg=st.binary(min_size=1, max_size=10_000), data=st.data())
    def test_tampered_signature_fails(self, keypair, msg, data):
        """Flipping one bit in the Ed25519 signature must fail verification.

        sign_bytes returns a base64-encoded 64-byte Ed25519 signature.
        Decode to raw bytes, tamper one bit, re-encode to base64.
        """
        private_key, public_key = keypair
        sig_b64 = sign_bytes(msg, private_key)
        sig_bytes = base64.b64decode(sig_b64)  # Ed25519 signature: always 64 bytes
        byte_idx = data.draw(st.integers(min_value=0, max_value=len(sig_bytes) - 1))
        bit_idx = data.draw(st.integers(min_value=0, max_value=7))
        tampered = bytearray(sig_bytes)
        tampered[byte_idx] ^= (1 << bit_idx)
        tampered_b64 = base64.b64encode(bytes(tampered)).decode("ascii")
        assert verify_signature(msg, tampered_b64, public_key) is False, (
            "verify_signature must reject a tampered Ed25519 signature"
        )


# ---- 8. Field count dispatch (external observation) ----

class TestFieldCountDispatch:
    """The cv field determines which receipt fields are hashed into the
    fingerprint. Tested by constructing pairs of receipts that differ
    ONLY in a field that is inside vs outside the cv-specific range:

    cv=5 (12 fields): parent_receipts is EXCLUDED.
      Receipts differing only in parent_receipts produce the SAME fingerprint.
    cv=6 (14 fields): parent_receipts IS included.
      Receipts differing only in parent_receipts produce DIFFERENT fingerprints.
    cv=7 (14 fields, same as cv=6): enforcement_surface is EXCLUDED.
      Receipts differing only in enforcement_surface produce the SAME fingerprint.
    cv=8 (16 fields): enforcement_surface IS included.
      Receipts differing only in enforcement_surface produce DIFFERENT fingerprints.
    cv=9 (20 fields): agent_identity is EXCLUDED.
      Adding agent_identity to the receipt dict does NOT change the fingerprint.
    cv=10 (21 fields): agent_identity IS included.
      Receipts differing only in agent_identity produce DIFFERENT fingerprints.

    Cite spec Section 4 for the cv/field-numbering.
    """

    def test_cv5_excludes_field_13_parent_receipts(self):
        """At cv=5, parent_receipts is outside the 12-field formula.

        Two cv=5 receipts identical in fields 1-12 but differing in
        parent_receipts must produce the SAME computed fingerprint.
        """
        r_null = _make_base_receipt("5")
        r_null["parent_receipts"] = None

        r_with = dict(r_null)
        r_with["parent_receipts"] = ["r_abc_001"]

        _, fp_null, _ = _verify_fingerprint_v013(r_null)
        _, fp_with, _ = _verify_fingerprint_v013(r_with)
        assert fp_null == fp_with, (
            "at cv=5, parent_receipts must NOT affect the fingerprint "
            "(field 13 is outside the 12-field formula)"
        )

    def test_cv6_includes_field_13_parent_receipts(self):
        """At cv=6, parent_receipts is field 13 (inside the 14-field formula).

        Two cv=6 receipts identical in fields 1-12 but differing in
        parent_receipts must produce DIFFERENT computed fingerprints.
        """
        r_null = _make_base_receipt("6")
        r_null["parent_receipts"] = None

        r_with = dict(r_null)
        r_with["parent_receipts"] = ["r_abc_001"]

        _, fp_null, _ = _verify_fingerprint_v013(r_null)
        _, fp_with, _ = _verify_fingerprint_v013(r_with)
        assert fp_null != fp_with, (
            "at cv=6, parent_receipts must affect the fingerprint "
            "(field 13 is inside the 14-field formula)"
        )

    def test_cv7_excludes_field_15_enforcement_surface(self):
        """At cv=7, enforcement_surface is outside the 14-field formula.

        Two cv=7 receipts differing only in enforcement_surface must
        produce the SAME computed fingerprint.
        """
        r_mid = _make_base_receipt("7")
        r_mid["enforcement_surface"] = "middleware"

        r_gw = dict(r_mid)
        r_gw["enforcement_surface"] = "gateway"

        _, fp_mid, _ = _verify_fingerprint_v013(r_mid)
        _, fp_gw, _ = _verify_fingerprint_v013(r_gw)
        assert fp_mid == fp_gw, (
            "at cv=7, enforcement_surface must NOT affect the fingerprint "
            "(field 15 is outside the 14-field formula)"
        )

    def test_cv8_includes_field_15_enforcement_surface(self):
        """At cv=8, enforcement_surface is field 15 (inside the 16-field formula).

        Two cv=8 receipts differing only in enforcement_surface must
        produce DIFFERENT computed fingerprints.
        """
        r_mid = _make_base_receipt("8")
        r_mid["enforcement_surface"] = "middleware"

        r_gw = dict(r_mid)
        r_gw["enforcement_surface"] = "gateway"

        _, fp_mid, _ = _verify_fingerprint_v013(r_mid)
        _, fp_gw, _ = _verify_fingerprint_v013(r_gw)
        assert fp_mid != fp_gw, (
            "at cv=8, enforcement_surface must affect the fingerprint "
            "(field 15 is inside the 16-field formula)"
        )

    def test_cv9_excludes_field_21_agent_identity(self):
        """At cv=9, agent_identity is absent (field 21 does not exist).

        Adding an agent_identity key to a cv=9 receipt dict does NOT
        change the computed fingerprint because the 20-field formula
        does not include it.
        """
        r_no_ai = _make_base_receipt("9")
        r_with_ai = dict(r_no_ai)
        r_with_ai["agent_identity"] = {"agent_session_id": "sn_ag_extra"}

        _, fp_no_ai, _ = _verify_fingerprint_v013(r_no_ai)
        _, fp_with_ai, _ = _verify_fingerprint_v013(r_with_ai)

        assert fp_no_ai != "", (
            "cv=9 receipt should produce a non-empty computed fingerprint"
        )
        assert fp_no_ai == fp_with_ai, (
            "at cv=9, agent_identity must NOT affect the fingerprint "
            "(field 21 exists only in the cv=10 formula)"
        )

    def test_cv10_includes_field_21_agent_identity(self):
        """At cv=10, agent_identity is field 21 (inside the 21-field formula).

        Two cv=10 receipts differing only in agent_identity must produce
        DIFFERENT computed fingerprints.
        """
        r_a = _make_base_receipt("10")
        r_a["agent_identity"] = {"agent_session_id": "sn_ag_alice_001"}

        r_b = dict(r_a)
        r_b["agent_identity"] = {"agent_session_id": "sn_ag_bob_001"}

        _, fp_a, _ = _verify_fingerprint_v013(r_a)
        _, fp_b, _ = _verify_fingerprint_v013(r_b)
        assert fp_a != fp_b, (
            "at cv=10, agent_identity must affect the fingerprint "
            "(field 21 is inside the 21-field formula)"
        )


# ---- 9. Redaction marker shape ----

class TestRedactionMarkerShape:
    """Per spec section 2.11.1, a redaction marker is exactly:
        {__redacted__: True, original_hash: <sha256-hex>}
    where original_hash is the SHA-256 hex digest of
    NFC(original_value).encode('utf-8') -- the full 64-hex digest.

    _make_redaction_marker is the canonical construction function.
    Its output must be byte-stable across logically equivalent inputs
    that differ only in NFC/NFD encoding.
    """

    @given(json_safe_text)
    def test_marker_structure(self, s):
        """_make_redaction_marker always returns the correct marker shape."""
        marker = _make_redaction_marker(s)
        assert marker.get("__redacted__") is True, (
            "marker must have __redacted__ = True"
        )
        h = marker.get("original_hash")
        assert isinstance(h, str), "original_hash must be a string"
        assert len(h) == 64, "original_hash must be a full 64-hex SHA-256 digest"
        assert all(c in "0123456789abcdef" for c in h), (
            "original_hash must be lowercase hex with no prefix"
        )

    @given(json_safe_text)
    def test_marker_hash_is_nfc_sha256(self, s):
        """original_hash equals SHA-256 of NFC(s).encode('utf-8')."""
        marker = _make_redaction_marker(s)
        nfc_s = unicodedata.normalize("NFC", s)
        expected = hashlib.sha256(nfc_s.encode("utf-8")).hexdigest()
        assert marker["original_hash"] == expected, (
            "original_hash must be SHA-256 of the NFC-normalized input"
        )

    @given(json_safe_text)
    def test_nfc_nfd_produce_same_marker_hash(self, s):
        """NFC and NFD forms of the same string produce the same marker hash.

        _make_redaction_marker normalizes to NFC before hashing, consistent
        with the hash_text NFC-normalization boundary in ADR-004.
        """
        nfc_s = unicodedata.normalize("NFC", s)
        nfd_s = unicodedata.normalize("NFD", s)
        marker_nfc = _make_redaction_marker(nfc_s)
        marker_nfd = _make_redaction_marker(nfd_s)
        assert marker_nfc["original_hash"] == marker_nfd["original_hash"], (
            "_make_redaction_marker must produce the same hash for "
            "NFC and NFD equivalents"
        )


# ---- 10. Fingerprint cross-site parity ----

class TestFingerprintCrossSiteParity:
    """Receipts generated by generate_receipt() pass verify_fingerprint().

    There is no single centralized compute_fingerprint callable in the
    Python SDK; the fingerprint formula is implemented inline in
    receipt.py (generate_receipt), middleware.py (_build_receipt_dict),
    and redaction.py (_apply_redaction_markers). The canonical
    re-computation path is verify.py (_verify_fingerprint_v013).

    This test uses the sample-input equality fallback: a receipt emitted
    by generate_receipt() must pass offline verification via
    verify_fingerprint(). If emission and verification have drifted to
    different formulas, the fingerprint mismatch surfaces here.

    Receipt-level signing is not exercised here (covered by
    test_crypto_integrity.py). Only fingerprint parity is tested.
    """

    def _make_trace(self, correlation_id: str) -> dict:
        return {
            "correlation_id": correlation_id,
            "observations": [],
            "output": None,
            "input": {},
        }

    def test_cv9_receipt_fingerprint_verifies(self):
        """cv=9 receipt from generate_receipt() passes verify_fingerprint()."""
        from sanna.receipt import generate_receipt, receipt_to_dict
        from sanna.verify import verify_fingerprint

        trace = self._make_trace("pbt-cv9-parity-001")
        receipt_obj = generate_receipt(trace)
        receipt_dict = receipt_to_dict(receipt_obj)

        matches, computed, expected = verify_fingerprint(receipt_dict)
        assert matches, (
            f"generate_receipt() produced a cv=9 receipt whose fingerprint "
            f"does not verify: computed={computed!r}, expected={expected!r}"
        )

    def test_cv10_receipt_fingerprint_verifies(self):
        """cv=10 receipt (with agent_identity) from generate_receipt() passes verify_fingerprint()."""
        from sanna.receipt import generate_receipt, receipt_to_dict
        from sanna.verify import verify_fingerprint

        trace = self._make_trace("pbt-cv10-parity-001")
        receipt_obj = generate_receipt(
            trace,
            enforcement_surface="gateway",
            invariants_scope="full",
            agent_identity={"agent_session_id": "sn_ag_pbt_parity_test"},
        )
        receipt_dict = receipt_to_dict(receipt_obj)

        matches, computed, expected = verify_fingerprint(receipt_dict)
        assert matches, (
            f"generate_receipt() produced a cv=10 receipt whose fingerprint "
            f"does not verify: computed={computed!r}, expected={expected!r}"
        )

    def test_full_and_short_fingerprint_both_verify(self):
        """verify_fingerprint checks both full_fingerprint (64-hex) and
        receipt_fingerprint (16-hex truncation). Formula drift between
        emission and verification would surface as a mismatch in either.
        """
        from sanna.receipt import generate_receipt, receipt_to_dict
        from sanna.verify import _verify_fingerprint_v013

        trace = self._make_trace("pbt-full-short-parity-001")
        receipt_obj = generate_receipt(trace)
        receipt_dict = receipt_to_dict(receipt_obj)

        matches, computed_short, stored_short = _verify_fingerprint_v013(receipt_dict)

        assert matches, (
            "full_fingerprint and receipt_fingerprint must both verify for a "
            "freshly generated cv=9 receipt"
        )
        assert computed_short == stored_short
        assert computed_short == receipt_dict["receipt_fingerprint"]
