"""
Sanna — Coherence checks for AI agents.

Generates portable, offline-verifiable "reasoning receipts" that document
AI agent decisions with C1-C5 coherence checks and consistency-verified hashing.
"""

from .version import __version__

from .hashing import hash_text, hash_obj, canonicalize_text
from .receipt import (
    generate_receipt,
    extract_trace_data,
    SannaReceipt,
    C3MReceipt,  # legacy alias
    CheckResult,
    FinalAnswerProvenance,
    ConstitutionProvenance,
    HaltEvent,
    TOOL_VERSION,
    SCHEMA_VERSION,
    CHECKS_VERSION,
)
from .verify import verify_receipt, load_schema, VerificationResult, verify_constitution_chain
from .middleware import (
    sanna_observe, SannaResult, SannaHaltError,
    build_trace_data, generate_constitution_receipt,
)
from .constitution import (
    Constitution,
    ConstitutionSignature,
    Boundary,
    HaltCondition,
    TrustTiers,
    TrustedSources,
    Provenance,
    AgentIdentity,
    IdentityClaim,
    IdentityVerificationResult,
    IdentityVerificationSummary,
    Invariant,
    AuthorityBoundaries,
    EscalationRule,
    EscalationTargetConfig,
    ApprovalRecord,
    ApprovalChain,
    ReasoningConfig,
    GLCCheckConfig,
    GLCMinimumSubstanceConfig,
    GLCNoParrotingConfig,
    GLCLLMCoherenceConfig,
    SannaConstitutionError,
    load_constitution,
    parse_constitution,
    validate_constitution_data,
    validate_against_schema,
    compute_constitution_hash,
    compute_content_hash,
    approve_constitution,
    verify_identity_claims,
    sign_constitution,
    constitution_to_receipt_ref,
    constitution_to_signable_dict,
    constitution_to_dict,
    save_constitution,
    scaffold_constitution,
)
from .enforcement import (
    CheckConfig,
    CustomInvariantRecord,
    configure_checks,
    INVARIANT_CHECK_MAP,
    CHECK_REGISTRY,
    AuthorityDecision,
    evaluate_authority,
    EscalationTarget,
    EscalationResult,
    execute_escalation,
    register_escalation_callback,
    clear_escalation_callbacks,
    get_escalation_callback,
)
from .crypto import (
    generate_keypair,
    load_key_metadata,
    sign_constitution_full,
    verify_constitution_full,
    sign_receipt,
    verify_receipt_signature,
    sanitize_for_signing,
)
from .bundle import (
    create_bundle,
    verify_bundle,
    BundleVerificationResult,
    BundleCheck,
)
from .store import ReceiptStore
from .evaluators import (
    register_invariant_evaluator,
    get_evaluator,
    list_evaluators,
    clear_evaluators,
)
from .drift import (
    DriftAnalyzer,
    DriftReport,
    AgentDriftSummary,
    CheckDriftDetail,
    export_drift_report,
    export_drift_report_to_file,
)
from .constitution_diff import (
    diff_constitutions,
    DiffResult,
    DiffEntry,
)

__all__ = [
    "__version__",
    "hash_text",
    "hash_obj",
    "canonicalize_text",
    "generate_receipt",
    "extract_trace_data",
    "SannaReceipt",
    "C3MReceipt",
    "CheckResult",
    "FinalAnswerProvenance",
    "ConstitutionProvenance",
    "HaltEvent",
    "verify_receipt",
    "load_schema",
    "VerificationResult",
    "verify_constitution_chain",
    "TOOL_VERSION",
    "SCHEMA_VERSION",
    "CHECKS_VERSION",
    "sanna_observe",
    "SannaResult",
    "SannaHaltError",
    "build_trace_data",
    "generate_constitution_receipt",
    "Constitution",
    "ConstitutionSignature",
    "Boundary",
    "HaltCondition",
    "TrustTiers",
    "TrustedSources",
    "Provenance",
    "AgentIdentity",
    "IdentityClaim",
    "IdentityVerificationResult",
    "IdentityVerificationSummary",
    "verify_identity_claims",
    "load_constitution",
    "parse_constitution",
    "validate_constitution_data",
    "validate_against_schema",
    "compute_constitution_hash",
    "sign_constitution",
    "constitution_to_receipt_ref",
    "constitution_to_signable_dict",
    "constitution_to_dict",
    "save_constitution",
    "scaffold_constitution",
    "Invariant",
    "AuthorityBoundaries",
    "EscalationRule",
    "EscalationTargetConfig",
    "ApprovalRecord",
    "ApprovalChain",
    "ReasoningConfig",
    "GLCCheckConfig",
    "GLCMinimumSubstanceConfig",
    "GLCNoParrotingConfig",
    "GLCLLMCoherenceConfig",
    "SannaConstitutionError",
    "compute_content_hash",
    "approve_constitution",
    "CheckConfig",
    "CustomInvariantRecord",
    "configure_checks",
    "INVARIANT_CHECK_MAP",
    "CHECK_REGISTRY",
    "AuthorityDecision",
    "evaluate_authority",
    "EscalationTarget",
    "EscalationResult",
    "execute_escalation",
    "register_escalation_callback",
    "clear_escalation_callbacks",
    "get_escalation_callback",
    "generate_keypair",
    "load_key_metadata",
    "sign_constitution_full",
    "verify_constitution_full",
    "sign_receipt",
    "verify_receipt_signature",
    "sanitize_for_signing",
    "create_bundle",
    "verify_bundle",
    "BundleVerificationResult",
    "BundleCheck",
    "ReceiptStore",
    "register_invariant_evaluator",
    "get_evaluator",
    "list_evaluators",
    "clear_evaluators",
    "DriftAnalyzer",
    "DriftReport",
    "AgentDriftSummary",
    "CheckDriftDetail",
    "export_drift_report",
    "export_drift_report_to_file",
    "diff_constitutions",
    "DiffResult",
    "DiffEntry",
]
