"""
Sanna — Coherence checks for AI agents.

Generates portable, offline-verifiable "reasoning receipts" that document
AI agent decisions with C1-C5 coherence checks and consistency-verified hashing.
"""

__version__ = "0.7.0"

from .hashing import hash_text, hash_obj, canonicalize_text
from .receipt import (
    generate_receipt,
    extract_trace_data,
    SannaReceipt,
    C3MReceipt,  # legacy alias
    CheckResult,
    FinalAnswerProvenance,
    ConstitutionProvenance,
    HaltEvent,
    TOOL_VERSION,
    SCHEMA_VERSION,
    CHECKS_VERSION,
)
from .verify import verify_receipt, load_schema, VerificationResult, verify_constitution_chain
from .middleware import sanna_observe, SannaResult, SannaHaltError
from .constitution import (
    Constitution,
    ConstitutionSignature,
    Boundary,
    HaltCondition,
    TrustTiers,
    TrustedSources,
    Provenance,
    AgentIdentity,
    Invariant,
    AuthorityBoundaries,
    EscalationRule,
    EscalationTargetConfig,
    SannaConstitutionError,
    load_constitution,
    parse_constitution,
    validate_constitution_data,
    validate_against_schema,
    compute_constitution_hash,
    sign_constitution,
    constitution_to_receipt_ref,
    constitution_to_signable_dict,
    constitution_to_dict,
    save_constitution,
    scaffold_constitution,
)
from .enforcement import (
    CheckConfig,
    CustomInvariantRecord,
    configure_checks,
    INVARIANT_CHECK_MAP,
    CHECK_REGISTRY,
    AuthorityDecision,
    evaluate_authority,
    EscalationTarget,
    EscalationResult,
    execute_escalation,
    register_escalation_callback,
    clear_escalation_callbacks,
    get_escalation_callback,
)
from .crypto import (
    generate_keypair,
    sign_constitution_full,
    verify_constitution_full,
    sign_receipt,
    verify_receipt_signature,
    sanitize_for_signing,
)
from .bundle import (
    create_bundle,
    verify_bundle,
    BundleVerificationResult,
    BundleCheck,
)

__all__ = [
    "__version__",
    "hash_text",
    "hash_obj",
    "canonicalize_text",
    "generate_receipt",
    "extract_trace_data",
    "SannaReceipt",
    "C3MReceipt",
    "CheckResult",
    "FinalAnswerProvenance",
    "ConstitutionProvenance",
    "HaltEvent",
    "verify_receipt",
    "load_schema",
    "VerificationResult",
    "verify_constitution_chain",
    "TOOL_VERSION",
    "SCHEMA_VERSION",
    "CHECKS_VERSION",
    "sanna_observe",
    "SannaResult",
    "SannaHaltError",
    "Constitution",
    "ConstitutionSignature",
    "Boundary",
    "HaltCondition",
    "TrustTiers",
    "TrustedSources",
    "Provenance",
    "AgentIdentity",
    "load_constitution",
    "parse_constitution",
    "validate_constitution_data",
    "validate_against_schema",
    "compute_constitution_hash",
    "sign_constitution",
    "constitution_to_receipt_ref",
    "constitution_to_signable_dict",
    "constitution_to_dict",
    "save_constitution",
    "scaffold_constitution",
    "Invariant",
    "AuthorityBoundaries",
    "EscalationRule",
    "EscalationTargetConfig",
    "SannaConstitutionError",
    "CheckConfig",
    "CustomInvariantRecord",
    "configure_checks",
    "INVARIANT_CHECK_MAP",
    "CHECK_REGISTRY",
    "AuthorityDecision",
    "evaluate_authority",
    "EscalationTarget",
    "EscalationResult",
    "execute_escalation",
    "register_escalation_callback",
    "clear_escalation_callbacks",
    "get_escalation_callback",
    "generate_keypair",
    "sign_constitution_full",
    "verify_constitution_full",
    "sign_receipt",
    "verify_receipt_signature",
    "sanitize_for_signing",
    "create_bundle",
    "verify_bundle",
    "BundleVerificationResult",
    "BundleCheck",
]
